/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as V1Dot2RouteImport } from './routes/v1[.]2'
import { Route as V1Dot1RouteImport } from './routes/v1[.]1'
import { Route as EcommerceRouteImport } from './routes/ecommerce'
import { Route as IndexRouteImport } from './routes/index'

const V1Dot2Route = V1Dot2RouteImport.update({
  id: '/v1.2',
  path: '/v1.2',
  getParentRoute: () => rootRouteImport,
} as any)
const V1Dot1Route = V1Dot1RouteImport.update({
  id: '/v1.1',
  path: '/v1.1',
  getParentRoute: () => rootRouteImport,
} as any)
const EcommerceRoute = EcommerceRouteImport.update({
  id: '/ecommerce',
  path: '/ecommerce',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ecommerce': typeof EcommerceRoute
  '/v1.1': typeof V1Dot1Route
  '/v1.2': typeof V1Dot2Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ecommerce': typeof EcommerceRoute
  '/v1.1': typeof V1Dot1Route
  '/v1.2': typeof V1Dot2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ecommerce': typeof EcommerceRoute
  '/v1.1': typeof V1Dot1Route
  '/v1.2': typeof V1Dot2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ecommerce' | '/v1.1' | '/v1.2'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ecommerce' | '/v1.1' | '/v1.2'
  id: '__root__' | '/' | '/ecommerce' | '/v1.1' | '/v1.2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EcommerceRoute: typeof EcommerceRoute
  V1Dot1Route: typeof V1Dot1Route
  V1Dot2Route: typeof V1Dot2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/v1.2': {
      id: '/v1.2'
      path: '/v1.2'
      fullPath: '/v1.2'
      preLoaderRoute: typeof V1Dot2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1.1': {
      id: '/v1.1'
      path: '/v1.1'
      fullPath: '/v1.1'
      preLoaderRoute: typeof V1Dot1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecommerce': {
      id: '/ecommerce'
      path: '/ecommerce'
      fullPath: '/ecommerce'
      preLoaderRoute: typeof EcommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EcommerceRoute: EcommerceRoute,
  V1Dot1Route: V1Dot1Route,
  V1Dot2Route: V1Dot2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
